name = "StructuredArrays"
uuid = "2e8cd123-6858-488d-b42d-068777248635"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.2.10"

[deps]
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
TypeUtils = "0.2, 0.3"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
